- title: $:/SiteTitle
  text: My TiddlyWiki
- title: $:/DefaultTiddlers
  text: Home

- title: $:/config/DefaultSidebarTab
  text: $:/core/ui/SideBar/Recent
- title: $:/config/RelinkOnRename
  text: "yes"
- title: $:/config/WikiParserRules/Inline/wikilink
  text: disable
- title: $:/themes/tiddlywiki/vanilla/options/codewrapping
  text: pre

- title: $:/config/PageControlButtons/Visibility/$:/core/ui/Buttons/home
  text: show
- title: $:/config/PageControlButtons/Visibility/$:/core/ui/Buttons/manager
  text: show
- title: $:/config/PageControlButtons/Visibility/$:/core/ui/Buttons/more-page-actions
  text: show
- title: $:/config/PageControlButtons/Visibility/$:/Mptw5/DownloadButton
  text: hide

- title: $:/config/ViewToolbarButtons/Visibility/$:/core/ui/Buttons/close-others
  text: show
- title: $:/config/ViewToolbarButtons/Visibility/$:/core/ui/Buttons/new-here
  text: show

# Disable some color schemes I don't think are very good.
# Override the palette shadow tiddlers with empty tiddlers.
- title: $:/palettes/Blanca
- title: $:/palettes/Blue
- title: $:/palettes/BrightMute
- title: $:/palettes/ContrastDark
- title: $:/palettes/ContrastLight
- title: $:/palettes/DarkPhotos
- title: $:/palettes/DesertSand
- title: $:/palettes/Muted
- title: $:/palettes/Rocker
- title: $:/palettes/SolarFlare
- title: $:/palettes/SpartanDay
- title: $:/palettes/SpartanNight
- title: $:/palettes/Twilight
- title: $:/palettes/Vanilla
