- title: $:/config/DefaultSidebarTab
  text: $:/core/ui/SideBar/Recent
- text: show
  title: $:/config/PageControlButtons/Visibility/$:/core/ui/Buttons/home
- text: show
  title: $:/config/PageControlButtons/Visibility/$:/core/ui/Buttons/manager
- text: show
  title: $:/config/PageControlButtons/Visibility/$:/core/ui/Buttons/more-page-actions
- text: "yes"
  title: $:/config/RelinkOnRename
- text: show
  title: $:/config/ViewToolbarButtons/Visibility/$:/core/ui/Buttons/close-others
- text: show
  title: $:/config/ViewToolbarButtons/Visibility/$:/core/ui/Buttons/new-here
- text: disable
  title: $:/config/WikiParserRules/Inline/wikilink
- title: $:/DefaultTiddlers
  text: Home
- title: $:/palette
  text: $:/palettes/GruvboxDark
- title: $:/themes/tiddlywiki/vanilla/options/codewrapping
  text: pre
